version: '3.7'
services:
  auditbeat:
    image: docker.elastic.co/beats/auditbeat:7.0.0
    command: auditbeat -e -strict.perms=false
    user: root
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    pid: "host"
    volumes:
    #   - ${PWD}/configs/auditbeat.docker.yml:/usr/share/auditbeat/auditbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elastic
  metricbeat:
      image: docker.elastic.co/beats/metricbeat:7.0.0
      # command: --strict.perms=false
      environment:
        - setup.kibana.host=kibana:5601
        - output.elasticsearch.hosts=["elasticsearch:9200"]
      cap_add:
        - AUDIT_CONTROL
        - AUDIT_READ
      volumes:
        # - ${PWD}/configs/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
        - /proc:/hostfs/proc:ro
        - /:/hostfs:ro
      networks:
        - elastic
  heartbeat:
      image: docker.elastic.co/beats/heartbeat:7.0.0
      command: --strict.perms=false
      environment:
        - setup.kibana.host=kibana:5601
        - output.elasticsearch.hosts=["elasticsearch:9200"]
      # volumes:
      #   - ${PWD}/configs/heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml
      networks:
        - elastic
  packetbeat:
      image: docker.elastic.co/beats/packetbeat:7.0.0
      command: --strict.perms=false
      environment:
        - setup.kibana.host=kibana:5601
        - output.elasticsearch.hosts=["elasticsearch:9200"]
      cap_add:
        - NET_RAW
        - NET_ADMIN
      # volumes:
      #   - ${PWD}/configs/packetbeat.docker.yml:/usr/share/packetbeat/packetbeat.yml
      networks:
        - elastic
  filebeat:
      image: docker.elastic.co/beats/filebeat:7.0.0
      command: --strict.perms=false
      environment:
        - setup.kibana.host=kibana:5601
        - output.elasticsearch.hosts=["elasticsearch:9200"]
      ports:
        - 9000:9000
      volumes:
        # - ${PWD}/configs/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - elastic