metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true
#       labels.dedot: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 2s
  enabled: true

- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - socket_summary  # Socket summary
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - filesystem     # File system usage for each mountpoint
    - fsstat         # File system summary metrics
    - raid           # Raid
    #- socket         # Sockets and connection info (linux only)
  enabled: true
  period: 2s
  processes: ['.*']

  ccpu.metrics: [percentages, normalized_percentages, ticks]
  core.metrics: ["percentages"] 
processors:
  # - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.kibana:
  host: "kibana:5601"
setup.dashboards.enabled: true
  # username: '${ELASTICSEARCH_USERNAME:}'
  # password: '${ELASTICSEARCH_PASSWORD:}'